version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.3
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login --region ap-south-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=015072495129.dkr.ecr.ap-south-1.amazonaws.com/test
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - echo URI
      - printf  '{"ImageURI":"'$REPOSITORY_URI':'$IMAGE_TAG'"}'
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"'$REPOSITORY_URI':'$IMAGE_TAG'"}' > imageDetail.json
artifacts:
  files:
    - imageDetail.json
